[package]
name = "test-rename-pkg"
description = "Test rename crates.io package"
license = "MIT"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
